Donguk/backend
boba-print/bcp-server-v4 pull request #4
Opened 2022-07-06 09:09 UTC by DONGUKwillsucceed

2022-07-06 13:44 UTC, KYUUUW requested changes
리뷰 완료했습니다. 아직 수정할게 많지만 실력이 느는게 눈에 보이네요 :) 고생 많으셨고, 앞으로도 화이팅 합니다!

2022-07-06 13:44 UTC, KYUUUW commented on src/module/user/user.controller.ts
> +  async remove(@Param('userId') userId: string) {
firebase auth 에서 user 를 disable 하는 기능이 있습니다. 그 로직을 추가로 작성해주시길 바랍니다.

2022-07-06 13:44 UTC, KYUUUW commented on src/module/user/user.controller.ts
> +  async remove(@Param('userId') userId: string) {
생각해보니 overlap 부분이랑 다른 쿼리하는 부분들 다 IsDeleted = 0 조건을 걸어주어야겠네요. 

이번 PR merge 이후 작업 진행해주시면 좋겠습니다.

2022-07-09 12:43 UTC, KYUUUW requested changes
우선 일차적으로 리뷰 드렸습니다.
수정 후 다시 리뷰해드리겠습니다.

2022-07-09 12:43 UTC, KYUUUW commented on src/module/print-job/service/create-printJob.service.ts
> +    const isValidateByEnum = await this.validatorWithEnum({
따로 함수를 만들지 말고 dto 에서 class validator 의 @Enum 기능을 활용바랍니다.

2022-07-09 12:43 UTC, KYUUUW commented on src/module/print-job/service/create-printJob.service.ts
> +    const isValidateByEnum = await this.validatorWithEnum({
유효성 검사의 책임은 controller 에 있습니다. service 에서는 validation 이 이미 된 데이터가 들어왔다고 가정합니다.

2022-07-09 12:43 UTC, KYUUUW commented on src/module/print-job/service/create-printJob.service.ts
> +      throw new HttpException('Wrongly formated', 400);
Service 에서 Http 관련 로직 사용하지 말아야 합니다.

2022-07-09 12:43 UTC, KYUUUW commented on src/module/print-job/service/create-printJob.service.ts
> +    const isPageRangesValidate = await this.pageRangesValidator(pageRanges);
class validator 에서 처리 바랍니다. 아마 `@Matches(pattern: RegExp, modifiers?: string)` 사용하면 됩니다.

2022-07-09 12:43 UTC, KYUUUW commented on src/module/print-job/service/create-printJob.service.ts
> +  private async validatorWithEnum(props: any) {
class validator 이용

2022-07-09 12:43 UTC, KYUUUW commented on src/module/print-job/service/create-printJob.service.ts
> +  private async pageRangesValidator(pageRange: string) {
regex 한줄로 검사할 수 있을 것 같은데 그렇지 않은 이유가 있나요?

2022-07-09 12:43 UTC, KYUUUW commented on src/module/print-job/service/create-printJob.service.ts
> +  private async pageRangesValidator(pageRange: string) {
다음부터 이런 코드는 주석 부탁드립니다.

2022-07-09 12:43 UTC, KYUUUW commented on src/module/print-job/service/create-printJob.service.ts
> +  private async randomNumGenerator() {
Math.random 을 사용하지 않은 이유가 있나요?

2022-07-09 12:43 UTC, KYUUUW commented on src/module/print-job/service/create-printJob.service.ts
> +  private async randomNumGenerator() {
함수 이름은 `<동사><목적어>` 형식이 더 보편적인 컨벤션입니다.
`<동사>...or` 의 합성어는 주로 class 에서 사용하는 컨벤션입니다.

수정 바랍니다.

2022-07-09 12:43 UTC, KYUUUW commented on src/module/print-job/service/create-printJob.service.ts
> +  private async checkOverlapPassword(userId: string, kioskId: string) {
check 라는 함수는 주로 boolean 형을 return 하는 컨벤션인데, 다른 더 좋은 이름 없을까요?

2022-07-09 12:43 UTC, KYUUUW commented on src/module/print-job/service/get-printJob.service.ts
> +  async findOne(params: any) {
정말 불가피한 상황을 제외하고는 any 사용을 금지하겠습니다.
이유는 검색하면 많이 나옵니다.... (여기 다 적기는 너무 장황해서....ㅠㅠ)

2022-07-09 12:43 UTC, KYUUUW commented on src/module/print-job/service/get-printJob.service.ts
> +    const queryResult = await this.prismaService.printJobs.findFirst({
아래 쿼리와 하나로 합칠 수 없나요??

2022-07-09 12:43 UTC, KYUUUW commented on src/module/print-job/service/get-printJob.service.ts
> +    const price = await this.priceCalculator(queryResult, Kiosks);
함수 naming convention (위의 설명과 같음)

2022-07-09 12:43 UTC, KYUUUW commented on src/module/print-job/service/get-printJob.service.ts
> +        order: queryResult.LayoutOrder as LayoutOrder,
class-transformer 사용하면 as 필요없음. dto 에서 string 을 enum 으로 바꿀 수 있습니다.

2022-07-10 06:13 UTC, DONGUKwillsucceed commented on src/module/print-job/service/create-printJob.service.ts
> +  private async randomNumGenerator() {
VerificationNumber는 string으로 알고있습니다. 그래서 첫번째 숫자가 0이 올 수도 있어서 math.random을 사용하지 않았습니다

2022-07-10 12:14 UTC, KYUUUW requested changes

2022-07-10 12:14 UTC, KYUUUW commented on src/module/print-job/print-job.controller.ts
>    @Get(':userId/print-jobs')
controller decorator 에 넣어서 중복 제거

2022-07-10 12:14 UTC, KYUUUW commented on src/module/print-job/print-job.controller.ts
>      }
위에 files 를 file 로 수정 -> 하나이기 때문에 단수

2022-07-10 12:14 UTC, KYUUUW commented on src/module/print-job/print-job.controller.ts
> +    const result = await this.validateRegex.validatePageRange(dto.pageRanges);
validate 하는 로직은 최대한 앞쪽으로

2022-07-10 12:14 UTC, KYUUUW commented on src/module/print-job/print-job.module.ts
> +    ValidateRegex,
Validator 네이밍

2022-07-10 12:14 UTC, KYUUUW commented on src/module/print-job/regex.validator.ts
> +      if (/^[0-9]+-[0-9]+$/.test(pageRange)) {
TODO 붙이기 -> regexp 를 최대한 활용한 validation

2022-07-10 12:14 UTC, KYUUUW commented on src/module/print-job/regex.validator.ts
> +export class ValidateRegex {
주석처리 바랍니다.

2022-07-10 12:14 UTC, KYUUUW commented on src/module/print-job/service/create-print-job.service.ts
> +    let verificationNumber = await this.getOverlapPassword(userId, kioskId);
password -> verficationNumber

2022-07-10 12:14 UTC, KYUUUW commented on src/module/print-job/service/create-print-job.service.ts
> +      const randomNumber = Math.floor(Math.random() * 99999);
`Math.floor(Math.random() * 90000 + 10000)`

2022-07-10 12:14 UTC, KYUUUW commented on src/module/print-job/service/create-print-job.service.ts
> +      PrintJobID: v4(),
v4 -> uuidv4()

2022-07-10 12:14 UTC, KYUUUW commented on src/module/print-job/service/create-print-job.service.ts
> +      throw new NotFoundException('not found!!');
에러

2022-07-10 12:14 UTC, KYUUUW commented on src/module/print-job/service/get-print-job.service.ts
> +      id: queryResults[0].PrintJobID,
상수하나 더 만들어서 `[0]` 없애기

2022-07-10 12:57 UTC, KYUUUW requested changes

2022-07-10 12:57 UTC, KYUUUW commented on src/module/print-job/print-job.controller.ts
>    @Get(':userId/print-jobs')
중복제거

2022-07-10 13:07 UTC, merged